rotor_wiring = ["EKMFLGDQVZNTOWYHXUSPAIBRCJ", "AJDKSIRUXBLHWTMCQGZNPYFVOE", "BDFHJLCPRTXVZNYEIWGAKMUSQO", "ESOVPZJAYQUIRHXLNFTGKDCMWB", "VZBRGITYUPSDNHLXAWMJQOFECK"]
rotor_turnovers = ["Q", "E", "V", "J", "Z"]
reflector_wiring = "YRUHQSLDPXNGOKMIEBFZCWVJAT"